#!/bin/sh
# invoke-uki-profilify.sh: to be installed as a mkinitcpio post hook

# invoke `uki-profilify` on UKI file newly generated by mkinitcpio
# only run if the preset actually made a UKI file
test -n $3 && uki-profilify $3
